CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910052015_InitialCreate') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'core') THEN
            CREATE SCHEMA core;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910052015_InitialCreate') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'security') THEN
            CREATE SCHEMA security;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910052015_InitialCreate') THEN
    CREATE TABLE core.locations (
        location_id integer GENERATED BY DEFAULT AS IDENTITY,
        location_code character varying(20) NOT NULL,
        location_name character varying(200) NOT NULL,
        location_type character varying(50) NOT NULL,
        address character varying(500),
        city character varying(100),
        province character varying(100),
        phone character varying(25),
        email character varying(100),
        is_active boolean NOT NULL,
        created_date timestamp with time zone NOT NULL,
        CONSTRAINT pk_locations PRIMARY KEY (location_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910052015_InitialCreate') THEN
    CREATE TABLE security.roles (
        role_id integer GENERATED BY DEFAULT AS IDENTITY,
        role_name character varying(50) NOT NULL,
        description character varying(200),
        permissions text NOT NULL,
        is_active boolean NOT NULL,
        created_date timestamp with time zone NOT NULL,
        CONSTRAINT pk_roles PRIMARY KEY (role_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910052015_InitialCreate') THEN
    CREATE TABLE security.users (
        user_id uuid NOT NULL,
        user_uuid uuid NOT NULL,
        user_code character varying(50) NOT NULL,
        first_name character varying(100),
        last_name character varying(100),
        full_name character varying(205) GENERATED ALWAYS AS (NULLIF(TRIM(COALESCE("first_name", '') || ' ' || COALESCE("last_name", '')), '')) STORED,
        date_of_birth timestamp with time zone,
        gender character varying(10),
        identity_number character varying(20),
        phone character varying(25),
        email character varying(100),
        address character varying(500),
        username character varying(50) NOT NULL,
        password_hash character varying(255),
        password_salt character varying(255),
        email_verified boolean NOT NULL,
        phone_verified boolean NOT NULL,
        id_social character varying(100),
        social_provider character varying(20),
        last_login_date timestamp with time zone,
        login_attempts integer NOT NULL,
        is_locked boolean NOT NULL,
        lock_until timestamp with time zone,
        is_active boolean NOT NULL,
        created_date timestamp with time zone NOT NULL,
        updated_date timestamp with time zone NOT NULL,
        image character varying(500),
        CONSTRAINT pk_users PRIMARY KEY (user_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910052015_InitialCreate') THEN
    CREATE TABLE security.staff (
        staff_id integer GENERATED BY DEFAULT AS IDENTITY,
        staff_code character varying(20) NOT NULL,
        username character varying(50) NOT NULL,
        password_hash character varying(255) NOT NULL,
        password_salt character varying(255) NOT NULL,
        full_name character varying(200) NOT NULL,
        email character varying(100) NOT NULL,
        phone character varying(25),
        location_id integer NOT NULL,
        role_id integer NOT NULL,
        is_active boolean NOT NULL,
        created_by integer NOT NULL,
        created_date timestamp with time zone NOT NULL,
        CONSTRAINT pk_staff PRIMARY KEY (staff_id),
        CONSTRAINT fk_staff_locations_location_id FOREIGN KEY (location_id) REFERENCES core.locations (location_id) ON DELETE RESTRICT,
        CONSTRAINT fk_staff_roles_role_id FOREIGN KEY (role_id) REFERENCES security.roles (role_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910052015_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_locations_location_code ON core.locations (location_code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910052015_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_roles_role_name ON security.roles (role_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910052015_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_staff_email ON security.staff (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910052015_InitialCreate') THEN
    CREATE INDEX ix_staff_location_id ON security.staff (location_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910052015_InitialCreate') THEN
    CREATE INDEX ix_staff_role_id ON security.staff (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910052015_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_staff_staff_code ON security.staff (staff_code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910052015_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_staff_username ON security.staff (username);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910052015_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_users_email ON security.users (email) WHERE email IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910052015_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_users_id_social ON security.users (id_social) WHERE id_social IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910052015_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_users_phone ON security.users (phone) WHERE phone IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910052015_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_users_user_code ON security.users (user_code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910052015_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_users_user_uuid ON security.users (user_uuid);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910052015_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_users_username ON security.users (username);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910052015_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260910052015_InitialCreate', '9.0.9');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910055441_AddDiscoveryAndScheduleItems') THEN
    CREATE TABLE core.discovery_items (
        discovery_item_id integer GENERATED BY DEFAULT AS IDENTITY,
        author_user_id integer NOT NULL,
        title character varying(200) NOT NULL,
        body text NOT NULL,
        category character varying(20) NOT NULL,
        reading_minutes integer NOT NULL,
        is_published boolean NOT NULL,
        created_date timestamp with time zone NOT NULL,
        CONSTRAINT pk_discovery_items PRIMARY KEY (discovery_item_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910055441_AddDiscoveryAndScheduleItems') THEN
    CREATE TABLE core.schedule_items (
        schedule_item_id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id uuid NOT NULL,
        title character varying(200) NOT NULL,
        location character varying(200) NOT NULL,
        start_at timestamp with time zone NOT NULL,
        is_done boolean NOT NULL,
        created_date timestamp with time zone NOT NULL,
        CONSTRAINT pk_schedule_items PRIMARY KEY (schedule_item_id),
        CONSTRAINT fk_schedule_items_users_user_id FOREIGN KEY (user_id) REFERENCES security.users (user_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910055441_AddDiscoveryAndScheduleItems') THEN
    CREATE INDEX ix_discovery_items_category ON core.discovery_items (category);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910055441_AddDiscoveryAndScheduleItems') THEN
    CREATE INDEX ix_discovery_items_is_published_created_date ON core.discovery_items (is_published, created_date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910055441_AddDiscoveryAndScheduleItems') THEN
    CREATE INDEX ix_schedule_items_user_id_start_at ON core.schedule_items (user_id, start_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910055441_AddDiscoveryAndScheduleItems') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260910055441_AddDiscoveryAndScheduleItems', '9.0.9');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910235147_AddFamily') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'family') THEN
            CREATE SCHEMA family;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910235147_AddFamily') THEN
    CREATE TABLE family.families (
        family_id uuid NOT NULL,
        family_uuid uuid NOT NULL,
        name character varying(120) NOT NULL,
        owner_user_id uuid NOT NULL,
        storage_quota_bytes bigint NOT NULL,
        is_active boolean NOT NULL,
        created_date timestamp with time zone NOT NULL,
        CONSTRAINT pk_families PRIMARY KEY (family_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910235147_AddFamily') THEN
    CREATE TABLE family.family_invites (
        family_invite_id uuid NOT NULL,
        family_id uuid NOT NULL,
        code character varying(16) NOT NULL,
        created_by_user_id uuid NOT NULL,
        expires_at timestamp with time zone NOT NULL,
        max_uses integer NOT NULL,
        used_count integer NOT NULL,
        revoked_at timestamp with time zone,
        created_date timestamp with time zone NOT NULL,
        CONSTRAINT pk_family_invites PRIMARY KEY (family_invite_id),
        CONSTRAINT fk_family_invites_families_family_id FOREIGN KEY (family_id) REFERENCES family.families (family_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910235147_AddFamily') THEN
    CREATE TABLE family.family_members (
        family_member_id uuid NOT NULL,
        family_id uuid NOT NULL,
        user_id uuid NOT NULL,
        member_role character varying(16) NOT NULL,
        display_name character varying(120),
        joined_date timestamp with time zone NOT NULL,
        is_active boolean NOT NULL,
        CONSTRAINT pk_family_members PRIMARY KEY (family_member_id),
        CONSTRAINT fk_family_members_families_family_id FOREIGN KEY (family_id) REFERENCES family.families (family_id) ON DELETE CASCADE,
        CONSTRAINT fk_family_members_users_user_id FOREIGN KEY (user_id) REFERENCES security.users (user_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910235147_AddFamily') THEN
    CREATE UNIQUE INDEX ix_families_family_uuid ON family.families (family_uuid);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910235147_AddFamily') THEN
    CREATE UNIQUE INDEX ix_family_invites_code ON family.family_invites (code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910235147_AddFamily') THEN
    CREATE INDEX ix_family_invites_family_id ON family.family_invites (family_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910235147_AddFamily') THEN
    CREATE UNIQUE INDEX ix_family_members_family_id_user_id ON family.family_members (family_id, user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910235147_AddFamily') THEN
    CREATE INDEX ix_family_members_user_id ON family.family_members (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260910235147_AddFamily') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260910235147_AddFamily', '9.0.9');
    END IF;
END $EF$;
COMMIT;

