-- File nay AUTO-GENERATED, KHONG sua tay. Sinh lai bang:
--   cd AioKin && dotnet ef migrations script -o ../db/init-postgres.sql
-- (khong dung --idempotent — day la script khoi tao 1 lan cho DB Supabase trong,
-- xem docs/database.md muc 2.1). Nguon su that la AioKin/Data/Migrations/, khong
-- phai file nay. Sinh lai lan nay (follow-up tag/variable-only versioning, migration
-- AddPromptMetaSig): them cot vault.prompts.meta_sig va cap nhat WHEN clause cua
-- trg_prompts_before_update de bump version/ghi sync_log ca khi CHI tag/variable
-- doi — xem .superpowers/sdd/followup-tag-variable-versioning-report.md.
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'core') THEN
        CREATE SCHEMA core;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'security') THEN
        CREATE SCHEMA security;
    END IF;
END $EF$;

CREATE TABLE core.locations (
    location_id integer GENERATED BY DEFAULT AS IDENTITY,
    location_code character varying(20) NOT NULL,
    location_name character varying(200) NOT NULL,
    location_type character varying(50) NOT NULL,
    address character varying(500),
    city character varying(100),
    province character varying(100),
    phone character varying(25),
    email character varying(100),
    is_active boolean NOT NULL,
    created_date timestamp with time zone NOT NULL,
    CONSTRAINT pk_locations PRIMARY KEY (location_id)
);

CREATE TABLE security.roles (
    role_id integer GENERATED BY DEFAULT AS IDENTITY,
    role_name character varying(50) NOT NULL,
    description character varying(200),
    permissions text NOT NULL,
    is_active boolean NOT NULL,
    created_date timestamp with time zone NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (role_id)
);

CREATE TABLE security.users (
    user_id uuid NOT NULL,
    user_uuid uuid NOT NULL,
    user_code character varying(50) NOT NULL,
    first_name character varying(100),
    last_name character varying(100),
    full_name character varying(205) GENERATED ALWAYS AS (NULLIF(TRIM(COALESCE("first_name", '') || ' ' || COALESCE("last_name", '')), '')) STORED,
    date_of_birth timestamp with time zone,
    gender character varying(10),
    identity_number character varying(20),
    phone character varying(25),
    email character varying(100),
    address character varying(500),
    username character varying(50) NOT NULL,
    password_hash character varying(255),
    password_salt character varying(255),
    email_verified boolean NOT NULL,
    phone_verified boolean NOT NULL,
    id_social character varying(100),
    social_provider character varying(20),
    last_login_date timestamp with time zone,
    login_attempts integer NOT NULL,
    is_locked boolean NOT NULL,
    lock_until timestamp with time zone,
    is_active boolean NOT NULL,
    created_date timestamp with time zone NOT NULL,
    updated_date timestamp with time zone NOT NULL,
    image character varying(500),
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE TABLE security.staff (
    staff_id integer GENERATED BY DEFAULT AS IDENTITY,
    staff_code character varying(20) NOT NULL,
    username character varying(50) NOT NULL,
    password_hash character varying(255) NOT NULL,
    password_salt character varying(255) NOT NULL,
    full_name character varying(200) NOT NULL,
    email character varying(100) NOT NULL,
    phone character varying(25),
    location_id integer NOT NULL,
    role_id integer NOT NULL,
    is_active boolean NOT NULL,
    created_by integer NOT NULL,
    created_date timestamp with time zone NOT NULL,
    CONSTRAINT pk_staff PRIMARY KEY (staff_id),
    CONSTRAINT fk_staff_locations_location_id FOREIGN KEY (location_id) REFERENCES core.locations (location_id) ON DELETE RESTRICT,
    CONSTRAINT fk_staff_roles_role_id FOREIGN KEY (role_id) REFERENCES security.roles (role_id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX ix_locations_location_code ON core.locations (location_code);

CREATE UNIQUE INDEX ix_roles_role_name ON security.roles (role_name);

CREATE UNIQUE INDEX ix_staff_email ON security.staff (email);

CREATE INDEX ix_staff_location_id ON security.staff (location_id);

CREATE INDEX ix_staff_role_id ON security.staff (role_id);

CREATE UNIQUE INDEX ix_staff_staff_code ON security.staff (staff_code);

CREATE UNIQUE INDEX ix_staff_username ON security.staff (username);

CREATE UNIQUE INDEX ix_users_email ON security.users (email) WHERE email IS NOT NULL;

CREATE UNIQUE INDEX ix_users_id_social ON security.users (id_social) WHERE id_social IS NOT NULL;

CREATE UNIQUE INDEX ix_users_phone ON security.users (phone) WHERE phone IS NOT NULL;

CREATE UNIQUE INDEX ix_users_user_code ON security.users (user_code);

CREATE UNIQUE INDEX ix_users_user_uuid ON security.users (user_uuid);

CREATE UNIQUE INDEX ix_users_username ON security.users (username);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260910052015_InitialCreate', '9.0.9');

CREATE TABLE core.discovery_items (
    discovery_item_id integer GENERATED BY DEFAULT AS IDENTITY,
    author_user_id integer NOT NULL,
    title character varying(200) NOT NULL,
    body text NOT NULL,
    category character varying(20) NOT NULL,
    reading_minutes integer NOT NULL,
    is_published boolean NOT NULL,
    created_date timestamp with time zone NOT NULL,
    CONSTRAINT pk_discovery_items PRIMARY KEY (discovery_item_id)
);

CREATE TABLE core.schedule_items (
    schedule_item_id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid NOT NULL,
    title character varying(200) NOT NULL,
    location character varying(200) NOT NULL,
    start_at timestamp with time zone NOT NULL,
    is_done boolean NOT NULL,
    created_date timestamp with time zone NOT NULL,
    CONSTRAINT pk_schedule_items PRIMARY KEY (schedule_item_id),
    CONSTRAINT fk_schedule_items_users_user_id FOREIGN KEY (user_id) REFERENCES security.users (user_id) ON DELETE CASCADE
);

CREATE INDEX ix_discovery_items_category ON core.discovery_items (category);

CREATE INDEX ix_discovery_items_is_published_created_date ON core.discovery_items (is_published, created_date);

CREATE INDEX ix_schedule_items_user_id_start_at ON core.schedule_items (user_id, start_at);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260910055441_AddDiscoveryAndScheduleItems', '9.0.9');

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'family') THEN
        CREATE SCHEMA family;
    END IF;
END $EF$;

CREATE TABLE family.families (
    family_id uuid NOT NULL,
    family_uuid uuid NOT NULL,
    name character varying(120) NOT NULL,
    owner_user_id uuid NOT NULL,
    storage_quota_bytes bigint NOT NULL,
    is_active boolean NOT NULL,
    created_date timestamp with time zone NOT NULL,
    CONSTRAINT pk_families PRIMARY KEY (family_id)
);

CREATE TABLE family.family_invites (
    family_invite_id uuid NOT NULL,
    family_id uuid NOT NULL,
    code character varying(16) NOT NULL,
    created_by_user_id uuid NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    max_uses integer NOT NULL,
    used_count integer NOT NULL,
    revoked_at timestamp with time zone,
    created_date timestamp with time zone NOT NULL,
    CONSTRAINT pk_family_invites PRIMARY KEY (family_invite_id),
    CONSTRAINT fk_family_invites_families_family_id FOREIGN KEY (family_id) REFERENCES family.families (family_id) ON DELETE CASCADE
);

CREATE TABLE family.family_members (
    family_member_id uuid NOT NULL,
    family_id uuid NOT NULL,
    user_id uuid NOT NULL,
    member_role character varying(16) NOT NULL,
    display_name character varying(120),
    joined_date timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT pk_family_members PRIMARY KEY (family_member_id),
    CONSTRAINT fk_family_members_families_family_id FOREIGN KEY (family_id) REFERENCES family.families (family_id) ON DELETE CASCADE,
    CONSTRAINT fk_family_members_users_user_id FOREIGN KEY (user_id) REFERENCES security.users (user_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_families_family_uuid ON family.families (family_uuid);

CREATE UNIQUE INDEX ix_family_invites_code ON family.family_invites (code);

CREATE INDEX ix_family_invites_family_id ON family.family_invites (family_id);

CREATE UNIQUE INDEX ix_family_members_family_id_user_id ON family.family_members (family_id, user_id);

CREATE INDEX ix_family_members_user_id ON family.family_members (user_id);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260910235147_AddFamily', '9.0.9');

CREATE TABLE security.device_credentials (
    device_credential_id uuid NOT NULL,
    user_id uuid NOT NULL,
    device_id character varying(100) NOT NULL,
    device_name character varying(120),
    platform character varying(20),
    public_key character varying(256) NOT NULL,
    created_date timestamp with time zone NOT NULL,
    last_used_date timestamp with time zone,
    revoked_at timestamp with time zone,
    CONSTRAINT pk_device_credentials PRIMARY KEY (device_credential_id),
    CONSTRAINT fk_device_credentials_users_user_id FOREIGN KEY (user_id) REFERENCES security.users (user_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_device_credentials_user_id_device_id ON security.device_credentials (user_id, device_id);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260925092551_AddDeviceCredentials', '9.0.9');

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'vault') THEN
        CREATE SCHEMA vault;
    END IF;
END $EF$;

CREATE TABLE vault.spaces (
    space_id uuid NOT NULL,
    space_uuid uuid NOT NULL,
    space_type integer NOT NULL,
    name character varying(120) NOT NULL,
    owner_user_id uuid NOT NULL,
    family_id uuid,
    is_active boolean NOT NULL,
    created_date timestamp with time zone NOT NULL,
    CONSTRAINT pk_spaces PRIMARY KEY (space_id),
    CONSTRAINT fk_spaces_families_family_id FOREIGN KEY (family_id) REFERENCES family.families (family_id) ON DELETE CASCADE,
    CONSTRAINT fk_spaces_users_owner_user_id FOREIGN KEY (owner_user_id) REFERENCES security.users (user_id) ON DELETE RESTRICT
);

CREATE TABLE vault.space_members (
    space_member_id uuid NOT NULL,
    space_id uuid NOT NULL,
    user_id uuid NOT NULL,
    member_role integer NOT NULL,
    joined_date timestamp with time zone NOT NULL,
    CONSTRAINT pk_space_members PRIMARY KEY (space_member_id),
    CONSTRAINT fk_space_members_spaces_space_id FOREIGN KEY (space_id) REFERENCES vault.spaces (space_id) ON DELETE CASCADE,
    CONSTRAINT fk_space_members_users_user_id FOREIGN KEY (user_id) REFERENCES security.users (user_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_space_members_space_id_user_id ON vault.space_members (space_id, user_id);

CREATE INDEX ix_space_members_user_id ON vault.space_members (user_id);

CREATE UNIQUE INDEX ix_spaces_family_id ON vault.spaces (family_id) WHERE family_id IS NOT NULL;

CREATE INDEX ix_spaces_owner_user_id ON vault.spaces (owner_user_id);

CREATE UNIQUE INDEX ix_spaces_space_uuid ON vault.spaces (space_uuid);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260925143447_AddPromptVaultSpaces', '9.0.9');

DROP INDEX vault.ix_spaces_owner_user_id;

CREATE UNIQUE INDEX ix_spaces_owner_personal_unique ON vault.spaces (owner_user_id) WHERE space_type = 0;

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260925145517_AddSpacesPersonalUniqueIndex', '9.0.9');

CREATE TABLE vault.categories (
    category_id uuid NOT NULL,
    space_id uuid NOT NULL,
    name character varying(80) NOT NULL,
    icon character varying(50),
    color character varying(20),
    sort_order integer NOT NULL,
    created_date timestamp with time zone NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (category_id),
    CONSTRAINT fk_categories_spaces_space_id FOREIGN KEY (space_id) REFERENCES vault.spaces (space_id) ON DELETE CASCADE
);

CREATE TABLE vault.tags (
    tag_id uuid NOT NULL,
    space_id uuid NOT NULL,
    name character varying(50) NOT NULL,
    created_date timestamp with time zone NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (tag_id),
    CONSTRAINT fk_tags_spaces_space_id FOREIGN KEY (space_id) REFERENCES vault.spaces (space_id) ON DELETE CASCADE
);

CREATE TABLE vault.prompts (
    prompt_id uuid NOT NULL,
    space_id uuid NOT NULL,
    category_id uuid,
    author_user_id uuid NOT NULL,
    title character varying(200) NOT NULL,
    content text NOT NULL,
    description character varying(500),
    is_favorite boolean NOT NULL,
    is_archived boolean NOT NULL,
    usage_count integer NOT NULL,
    content_size_bytes integer,
    is_externalized boolean NOT NULL,
    content_storage_path character varying(500),
    version integer NOT NULL,
    is_deleted boolean NOT NULL,
    has_conflict boolean NOT NULL,
    created_date timestamp with time zone NOT NULL,
    updated_date timestamp with time zone NOT NULL,
    updated_device_id character varying(100),
    CONSTRAINT pk_prompts PRIMARY KEY (prompt_id),
    CONSTRAINT fk_prompts_categories_category_id FOREIGN KEY (category_id) REFERENCES vault.categories (category_id) ON DELETE SET NULL,
    CONSTRAINT fk_prompts_spaces_space_id FOREIGN KEY (space_id) REFERENCES vault.spaces (space_id) ON DELETE CASCADE,
    CONSTRAINT fk_prompts_users_author_user_id FOREIGN KEY (author_user_id) REFERENCES security.users (user_id) ON DELETE RESTRICT
);

CREATE TABLE vault.prompt_tags (
    prompt_id uuid NOT NULL,
    tag_id uuid NOT NULL,
    CONSTRAINT pk_prompt_tags PRIMARY KEY (prompt_id, tag_id),
    CONSTRAINT fk_prompt_tags_prompts_prompt_id FOREIGN KEY (prompt_id) REFERENCES vault.prompts (prompt_id) ON DELETE CASCADE,
    CONSTRAINT fk_prompt_tags_tags_tag_id FOREIGN KEY (tag_id) REFERENCES vault.tags (tag_id) ON DELETE CASCADE
);

CREATE TABLE vault.prompt_variables (
    variable_id uuid NOT NULL,
    prompt_id uuid NOT NULL,
    var_key character varying(50) NOT NULL,
    label character varying(100),
    default_value character varying(500),
    var_type character varying(20) NOT NULL,
    options text,
    sort_order integer NOT NULL,
    CONSTRAINT pk_prompt_variables PRIMARY KEY (variable_id),
    CONSTRAINT fk_prompt_variables_prompts_prompt_id FOREIGN KEY (prompt_id) REFERENCES vault.prompts (prompt_id) ON DELETE CASCADE
);

CREATE INDEX ix_categories_space_id ON vault.categories (space_id);

CREATE UNIQUE INDEX ix_categories_space_id_name ON vault.categories (space_id, name);

CREATE INDEX ix_prompt_tags_tag_id ON vault.prompt_tags (tag_id);

CREATE INDEX ix_prompt_variables_prompt_id ON vault.prompt_variables (prompt_id);

CREATE UNIQUE INDEX ix_prompt_variables_prompt_id_var_key ON vault.prompt_variables (prompt_id, var_key);

CREATE INDEX ix_prompts_author_user_id ON vault.prompts (author_user_id);

CREATE INDEX ix_prompts_category_id ON vault.prompts (category_id);

CREATE INDEX ix_prompts_space_id ON vault.prompts (space_id);

CREATE INDEX ix_prompts_space_id_is_favorite ON vault.prompts (space_id, is_favorite) WHERE is_deleted = false;

CREATE INDEX ix_prompts_space_id_updated_date ON vault.prompts (space_id, updated_date) WHERE is_deleted = false;

CREATE INDEX ix_tags_space_id ON vault.tags (space_id);

CREATE UNIQUE INDEX ix_tags_space_id_name ON vault.tags (space_id, name);

CREATE INDEX ix_prompts_fts ON vault.prompts USING GIN (to_tsvector('simple', title || ' ' || content));

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260925185031_AddPromptVaultDomain', '9.0.9');

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'sync') THEN
        CREATE SCHEMA sync;
    END IF;
END $EF$;

CREATE TABLE sync.backup_snapshots (
    snapshot_id uuid NOT NULL,
    space_id uuid NOT NULL,
    triggered_by_user_id uuid NOT NULL,
    snapshot_type character varying(20) NOT NULL,
    storage_path character varying(500) NOT NULL,
    file_size_bytes bigint,
    prompt_count integer,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_backup_snapshots PRIMARY KEY (snapshot_id)
);

CREATE TABLE sync.devices (
    user_id uuid NOT NULL,
    device_id character varying(100) NOT NULL,
    device_name character varying(120),
    platform character varying(20),
    app_version character varying(20),
    last_synced_at timestamp with time zone,
    is_stale boolean NOT NULL,
    created_date timestamp with time zone NOT NULL,
    CONSTRAINT pk_devices PRIMARY KEY (user_id, device_id)
);

CREATE TABLE sync.sync_conflicts (
    conflict_id uuid NOT NULL,
    entity_type character varying(30) NOT NULL,
    entity_id uuid NOT NULL,
    local_payload_json jsonb NOT NULL,
    remote_payload_json jsonb NOT NULL,
    local_version integer NOT NULL,
    remote_version integer NOT NULL,
    resolved boolean NOT NULL,
    resolution_strategy character varying(20),
    resolved_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_sync_conflicts PRIMARY KEY (conflict_id)
);

CREATE TABLE sync.sync_log (
    sync_log_id bigint GENERATED BY DEFAULT AS IDENTITY,
    space_id uuid NOT NULL,
    entity_type character varying(30) NOT NULL,
    entity_id uuid NOT NULL,
    operation character varying(10) NOT NULL,
    payload jsonb,
    origin_device_id character varying(100),
    version integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT pk_sync_log PRIMARY KEY (sync_log_id)
);

CREATE INDEX ix_backup_snapshots_space_id_created_at ON sync.backup_snapshots (space_id, created_at DESC);

CREATE INDEX ix_devices_last_synced_at ON sync.devices (last_synced_at) WHERE is_stale = false;

CREATE INDEX ix_sync_conflicts_entity_type_entity_id ON sync.sync_conflicts (entity_type, entity_id) WHERE resolved = false;

CREATE INDEX ix_sync_log_entity_type_entity_id ON sync.sync_log (entity_type, entity_id);

CREATE INDEX ix_sync_log_space_id_created_at ON sync.sync_log (space_id, created_at);

CREATE OR REPLACE FUNCTION vault.fn_prompts_before_update()
RETURNS TRIGGER AS $$
BEGIN
    NEW.version := OLD.version + 1;
    NEW.updated_date := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_prompts_before_update
    BEFORE UPDATE ON vault.prompts
    FOR EACH ROW
    WHEN (
        OLD.title IS DISTINCT FROM NEW.title OR
        OLD.content IS DISTINCT FROM NEW.content OR
        OLD.description IS DISTINCT FROM NEW.description OR
        OLD.category_id IS DISTINCT FROM NEW.category_id OR
        OLD.is_deleted IS DISTINCT FROM NEW.is_deleted
    )
    EXECUTE FUNCTION vault.fn_prompts_before_update();

CREATE OR REPLACE FUNCTION sync.fn_prompts_write_log()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO sync.sync_log (space_id, entity_type, entity_id, operation, payload, origin_device_id, version)
    VALUES (
        COALESCE(NEW.space_id, OLD.space_id),
        'prompt',
        COALESCE(NEW.prompt_id, OLD.prompt_id),
        LOWER(TG_OP),
        CASE WHEN TG_OP = 'DELETE' THEN to_jsonb(OLD) ELSE to_jsonb(NEW) END,
        COALESCE(NEW.updated_device_id, OLD.updated_device_id),
        COALESCE(NEW.version, OLD.version)
    );
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

-- Trigger 2: ghi sync_log. Postgres KHONG cho WHEN cua mot trigger INSERT
-- (ke ca khi gop chung voi UPDATE/DELETE trong mot CREATE TRIGGER) tham chieu
-- OLD ("42P17: INSERT trigger's WHEN condition cannot reference OLD values"),
-- va cung khong cho WHEN dung bien TG_OP ("42703: column tg_op does not
-- exist" — TG_OP chi ton tai trong than ham PL/pgSQL). Vi vay tach thanh 3
-- trigger rieng theo tung loai thao tac thay vi 1 trigger gop dieu kien TG_OP:
--   - INSERT/DELETE: luon ghi log, khong dieu kien.
--   - UPDATE: CHI ghi khi version thuc su tang (P10) — vi trigger 1 chi bump
--     version tren thay doi noi dung that su (bao gom ca is_deleted, P11), dieu
--     kien "version co doi" tuong duong voi "day la mot content change that",
--     nen mot write CHI bat has_conflict/is_favorite (khong lam version nhich
--     len) se khong con tao them dong sync_log gia.
CREATE TRIGGER trg_prompts_write_sync_log_ins
    AFTER INSERT ON vault.prompts
    FOR EACH ROW
    EXECUTE FUNCTION sync.fn_prompts_write_log();

CREATE TRIGGER trg_prompts_write_sync_log_upd
    AFTER UPDATE ON vault.prompts
    FOR EACH ROW
    WHEN (OLD.version IS DISTINCT FROM NEW.version)
    EXECUTE FUNCTION sync.fn_prompts_write_log();

CREATE TRIGGER trg_prompts_write_sync_log_del
    AFTER DELETE ON vault.prompts
    FOR EACH ROW
    EXECUTE FUNCTION sync.fn_prompts_write_log();

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260925194111_AddSyncEngine', '9.0.9');

ALTER TABLE sync.sync_log ADD origin_user_id uuid;

ALTER TABLE vault.prompts ADD updated_by_user_id uuid;

CREATE OR REPLACE FUNCTION sync.fn_prompts_write_log()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO sync.sync_log (space_id, entity_type, entity_id, operation, payload, origin_device_id, origin_user_id, version)
    VALUES (
        COALESCE(NEW.space_id, OLD.space_id),
        'prompt',
        COALESCE(NEW.prompt_id, OLD.prompt_id),
        LOWER(TG_OP),
        CASE WHEN TG_OP = 'DELETE' THEN to_jsonb(OLD) ELSE to_jsonb(NEW) END,
        COALESCE(NEW.updated_device_id, OLD.updated_device_id),
        COALESCE(NEW.updated_by_user_id, OLD.updated_by_user_id),
        COALESCE(NEW.version, OLD.version)
    );
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260925234505_AddSyncLogOriginUser', '9.0.9');

ALTER TABLE sync.sync_conflicts ADD local_operation character varying(10) NOT NULL DEFAULT '';

ALTER TABLE sync.sync_conflicts ADD remote_is_deleted boolean NOT NULL DEFAULT FALSE;

ALTER TABLE sync.sync_conflicts ADD space_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260926003505_AddSyncConflictOperationMetadata', '9.0.9');

ALTER TABLE vault.prompts ADD meta_sig character varying(64);

DROP TRIGGER IF EXISTS trg_prompts_before_update ON vault.prompts;

CREATE OR REPLACE FUNCTION vault.fn_prompts_before_update()
RETURNS TRIGGER AS $$
BEGIN
    NEW.version := OLD.version + 1;
    NEW.updated_date := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_prompts_before_update
    BEFORE UPDATE ON vault.prompts
    FOR EACH ROW
    WHEN (
        OLD.title IS DISTINCT FROM NEW.title OR
        OLD.content IS DISTINCT FROM NEW.content OR
        OLD.description IS DISTINCT FROM NEW.description OR
        OLD.category_id IS DISTINCT FROM NEW.category_id OR
        OLD.is_deleted IS DISTINCT FROM NEW.is_deleted OR
        OLD.meta_sig IS DISTINCT FROM NEW.meta_sig
    )
    EXECUTE FUNCTION vault.fn_prompts_before_update();

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260926063044_AddPromptMetaSig', '9.0.9');

CREATE TABLE security.data_protection_keys (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    friendly_name text,
    xml text,
    CONSTRAINT pk_data_protection_keys PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260926210353_AddDataProtectionKeys', '9.0.9');

COMMIT;

