// <auto-generated />
using System;
using AioKin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AioKin.Data.Migrations
{
    [DbContext(typeof(AioKinDbContext))]
    [Migration("20260925234505_AddSyncLogOriginUser")]
    partial class AddSyncLogOriginUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AioKin.Data.Entities.Core.DiscoveryItem", b =>
                {
                    b.Property<int>("DiscoveryItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("discovery_item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DiscoveryItemID"));

                    b.Property<int>("AuthorUserID")
                        .HasColumnType("integer")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<int>("ReadingMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("reading_minutes");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("DiscoveryItemID")
                        .HasName("pk_discovery_items");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_discovery_items_category");

                    b.HasIndex("IsPublished", "CreatedDate")
                        .HasDatabaseName("ix_discovery_items_is_published_created_date");

                    b.ToTable("discovery_items", "core");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Core.Location", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LocationID"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("location_code");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location_name");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("location_type");

                    b.Property<string>("Phone")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("phone");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("province");

                    b.HasKey("LocationID")
                        .HasName("pk_locations");

                    b.HasIndex("LocationCode")
                        .IsUnique()
                        .HasDatabaseName("ix_locations_location_code");

                    b.ToTable("locations", "core");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Core.ScheduleItem", b =>
                {
                    b.Property<int>("ScheduleItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("schedule_item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScheduleItemID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean")
                        .HasColumnName("is_done");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ScheduleItemID")
                        .HasName("pk_schedule_items");

                    b.HasIndex("UserID", "StartAt")
                        .HasDatabaseName("ix_schedule_items_user_id_start_at");

                    b.ToTable("schedule_items", "core");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Family.Family", b =>
                {
                    b.Property<Guid>("FamilyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid>("FamilyUUID")
                        .HasColumnType("uuid")
                        .HasColumnName("family_uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserID")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<long>("StorageQuotaBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("storage_quota_bytes");

                    b.HasKey("FamilyID")
                        .HasName("pk_families");

                    b.HasIndex("FamilyUUID")
                        .IsUnique()
                        .HasDatabaseName("ix_families_family_uuid");

                    b.ToTable("families", "family");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Family.FamilyInvite", b =>
                {
                    b.Property<Guid>("FamilyInviteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("family_invite_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<Guid>("CreatedByUserID")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyID")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<int>("MaxUses")
                        .HasColumnType("integer")
                        .HasColumnName("max_uses");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer")
                        .HasColumnName("used_count");

                    b.HasKey("FamilyInviteID")
                        .HasName("pk_family_invites");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_family_invites_code");

                    b.HasIndex("FamilyID")
                        .HasDatabaseName("ix_family_invites_family_id");

                    b.ToTable("family_invites", "family");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Family.FamilyMember", b =>
                {
                    b.Property<Guid>("FamilyMemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("family_member_id");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("FamilyID")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_date");

                    b.Property<string>("MemberRole")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("member_role");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("FamilyMemberID")
                        .HasName("pk_family_members");

                    b.HasIndex("UserID")
                        .HasDatabaseName("ix_family_members_user_id");

                    b.HasIndex("FamilyID", "UserID")
                        .IsUnique()
                        .HasDatabaseName("ix_family_members_family_id_user_id");

                    b.ToTable("family_members", "family");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Security.DeviceCredential", b =>
                {
                    b.Property<Guid>("DeviceCredentialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("device_credential_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("device_name");

                    b.Property<DateTime?>("LastUsedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_date");

                    b.Property<string>("Platform")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("platform");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("public_key");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("DeviceCredentialID")
                        .HasName("pk_device_credentials");

                    b.HasIndex("UserID", "DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_device_credentials_user_id_device_id");

                    b.ToTable("device_credentials", "security");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Security.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permissions");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleID")
                        .HasName("pk_roles");

                    b.HasIndex("RoleName")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_role_name");

                    b.ToTable("roles", "security");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Security.Staff", b =>
                {
                    b.Property<int>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("staff_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StaffID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("LocationID")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_salt");

                    b.Property<string>("Phone")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("phone");

                    b.Property<int>("RoleID")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("StaffCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("staff_code");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("StaffID")
                        .HasName("pk_staff");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_email");

                    b.HasIndex("LocationID")
                        .HasDatabaseName("ix_staff_location_id");

                    b.HasIndex("RoleID")
                        .HasDatabaseName("ix_staff_role_id");

                    b.HasIndex("StaffCode")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_staff_code");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_username");

                    b.ToTable("staff", "security");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Security.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(205)
                        .HasColumnType("character varying(205)")
                        .HasColumnName("full_name")
                        .HasComputedColumnSql("NULLIF(TRIM(COALESCE(\"first_name\", '') || ' ' || COALESCE(\"last_name\", '')), '')", true);

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gender");

                    b.Property<string>("IDSocial")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id_social");

                    b.Property<string>("IdentityNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("identity_number");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_date");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lock_until");

                    b.Property<int>("LoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("login_attempts");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_salt");

                    b.Property<string>("Phone")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("phone");

                    b.Property<bool>("PhoneVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_verified");

                    b.Property<string>("SocialProvider")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("social_provider");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_code");

                    b.Property<Guid>("UserUUID")
                        .HasColumnType("uuid")
                        .HasColumnName("user_uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("UserID")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("IDSocial")
                        .IsUnique()
                        .HasDatabaseName("ix_users_id_social")
                        .HasFilter("id_social IS NOT NULL");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ix_users_phone")
                        .HasFilter("phone IS NOT NULL");

                    b.HasIndex("UserCode")
                        .IsUnique()
                        .HasDatabaseName("ix_users_user_code");

                    b.HasIndex("UserUUID")
                        .IsUnique()
                        .HasDatabaseName("ix_users_user_uuid");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", "security");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Sync.BackupSnapshot", b =>
                {
                    b.Property<Guid>("SnapshotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<int?>("PromptCount")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_count");

                    b.Property<string>("SnapshotType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("snapshot_type");

                    b.Property<Guid>("SpaceID")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_path");

                    b.Property<Guid>("TriggeredByUserID")
                        .HasColumnType("uuid")
                        .HasColumnName("triggered_by_user_id");

                    b.HasKey("SnapshotID")
                        .HasName("pk_backup_snapshots");

                    b.HasIndex("SpaceID", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_backup_snapshots_space_id_created_at");

                    b.ToTable("backup_snapshots", "sync");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Sync.Device", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("DeviceID")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("app_version");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("device_name");

                    b.Property<bool>("IsStale")
                        .HasColumnType("boolean")
                        .HasColumnName("is_stale");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Platform")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("platform");

                    b.HasKey("UserID", "DeviceID")
                        .HasName("pk_devices");

                    b.HasIndex("LastSyncedAt")
                        .HasDatabaseName("ix_devices_last_synced_at")
                        .HasFilter("is_stale = false");

                    b.ToTable("devices", "sync");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Sync.SyncConflict", b =>
                {
                    b.Property<Guid>("ConflictID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("conflict_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("entity_type");

                    b.Property<string>("LocalPayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("local_payload_json");

                    b.Property<int>("LocalVersion")
                        .HasColumnType("integer")
                        .HasColumnName("local_version");

                    b.Property<string>("RemotePayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("remote_payload_json");

                    b.Property<int>("RemoteVersion")
                        .HasColumnType("integer")
                        .HasColumnName("remote_version");

                    b.Property<string>("ResolutionStrategy")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("resolution_strategy");

                    b.Property<bool>("Resolved")
                        .HasColumnType("boolean")
                        .HasColumnName("resolved");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.HasKey("ConflictID")
                        .HasName("pk_sync_conflicts");

                    b.HasIndex("EntityType", "EntityID")
                        .HasDatabaseName("ix_sync_conflicts_entity_type_entity_id")
                        .HasFilter("resolved = false");

                    b.ToTable("sync_conflicts", "sync");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Sync.SyncLogEntry", b =>
                {
                    b.Property<long>("SyncLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sync_log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SyncLogID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("operation");

                    b.Property<string>("OriginDeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("origin_device_id");

                    b.Property<Guid?>("OriginUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("origin_user_id");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("SpaceID")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("SyncLogID")
                        .HasName("pk_sync_log");

                    b.HasIndex("EntityType", "EntityID")
                        .HasDatabaseName("ix_sync_log_entity_type_entity_id");

                    b.HasIndex("SpaceID", "CreatedAt")
                        .HasDatabaseName("ix_sync_log_space_id_created_at");

                    b.ToTable("sync_log", "sync");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Vault.Category", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("SpaceID")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id");

                    b.HasKey("CategoryID")
                        .HasName("pk_categories");

                    b.HasIndex("SpaceID")
                        .HasDatabaseName("ix_categories_space_id");

                    b.HasIndex("SpaceID", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_space_id_name");

                    b.ToTable("categories", "promptvault");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Vault.Prompt", b =>
                {
                    b.Property<Guid>("PromptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("prompt_id");

                    b.Property<Guid>("AuthorUserID")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<Guid?>("CategoryID")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int?>("ContentSizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("content_size_bytes");

                    b.Property<string>("ContentStoragePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("content_storage_path");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("HasConflict")
                        .HasColumnType("boolean")
                        .HasColumnName("has_conflict");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsExternalized")
                        .HasColumnType("boolean")
                        .HasColumnName("is_externalized");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_favorite");

                    b.Property<Guid>("SpaceID")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UpdatedDeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_device_id");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer")
                        .HasColumnName("usage_count");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("PromptID")
                        .HasName("pk_prompts");

                    b.HasIndex("AuthorUserID")
                        .HasDatabaseName("ix_prompts_author_user_id");

                    b.HasIndex("CategoryID")
                        .HasDatabaseName("ix_prompts_category_id");

                    b.HasIndex("SpaceID")
                        .HasDatabaseName("ix_prompts_space_id");

                    b.HasIndex("SpaceID", "IsFavorite")
                        .HasDatabaseName("ix_prompts_space_id_is_favorite")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("SpaceID", "UpdatedDate")
                        .HasDatabaseName("ix_prompts_space_id_updated_date")
                        .HasFilter("is_deleted = false");

                    b.ToTable("prompts", "promptvault");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Vault.PromptTag", b =>
                {
                    b.Property<Guid>("PromptID")
                        .HasColumnType("uuid")
                        .HasColumnName("prompt_id");

                    b.Property<Guid>("TagID")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("PromptID", "TagID")
                        .HasName("pk_prompt_tags");

                    b.HasIndex("TagID")
                        .HasDatabaseName("ix_prompt_tags_tag_id");

                    b.ToTable("prompt_tags", "promptvault");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Vault.PromptVariable", b =>
                {
                    b.Property<Guid>("VariableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("variable_id");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("default_value");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<string>("Options")
                        .HasColumnType("text")
                        .HasColumnName("options");

                    b.Property<Guid>("PromptID")
                        .HasColumnType("uuid")
                        .HasColumnName("prompt_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("VarKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("var_key");

                    b.Property<string>("VarType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("var_type");

                    b.HasKey("VariableID")
                        .HasName("pk_prompt_variables");

                    b.HasIndex("PromptID")
                        .HasDatabaseName("ix_prompt_variables_prompt_id");

                    b.HasIndex("PromptID", "VarKey")
                        .IsUnique()
                        .HasDatabaseName("ix_prompt_variables_prompt_id_var_key");

                    b.ToTable("prompt_variables", "promptvault");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Vault.Space", b =>
                {
                    b.Property<Guid>("SpaceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("space_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid?>("FamilyID")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserID")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("SpaceType")
                        .HasColumnType("integer")
                        .HasColumnName("space_type");

                    b.Property<Guid>("SpaceUUID")
                        .HasColumnType("uuid")
                        .HasColumnName("space_uuid");

                    b.HasKey("SpaceID")
                        .HasName("pk_spaces");

                    b.HasIndex("FamilyID")
                        .IsUnique()
                        .HasDatabaseName("ix_spaces_family_id")
                        .HasFilter("family_id IS NOT NULL");

                    b.HasIndex("OwnerUserID")
                        .IsUnique()
                        .HasDatabaseName("ix_spaces_owner_personal_unique")
                        .HasFilter("space_type = 0");

                    b.HasIndex("SpaceUUID")
                        .IsUnique()
                        .HasDatabaseName("ix_spaces_space_uuid");

                    b.ToTable("spaces", "promptvault");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Vault.SpaceMember", b =>
                {
                    b.Property<Guid>("SpaceMemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("space_member_id");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_date");

                    b.Property<int>("MemberRole")
                        .HasColumnType("integer")
                        .HasColumnName("member_role");

                    b.Property<Guid>("SpaceID")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("SpaceMemberID")
                        .HasName("pk_space_members");

                    b.HasIndex("UserID")
                        .HasDatabaseName("ix_space_members_user_id");

                    b.HasIndex("SpaceID", "UserID")
                        .IsUnique()
                        .HasDatabaseName("ix_space_members_space_id_user_id");

                    b.ToTable("space_members", "promptvault");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Vault.Tag", b =>
                {
                    b.Property<Guid>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<Guid>("SpaceID")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id");

                    b.HasKey("TagID")
                        .HasName("pk_tags");

                    b.HasIndex("SpaceID")
                        .HasDatabaseName("ix_tags_space_id");

                    b.HasIndex("SpaceID", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_space_id_name");

                    b.ToTable("tags", "promptvault");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Core.ScheduleItem", b =>
                {
                    b.HasOne("AioKin.Data.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_items_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Family.FamilyInvite", b =>
                {
                    b.HasOne("AioKin.Data.Entities.Family.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_family_invites_families_family_id");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Family.FamilyMember", b =>
                {
                    b.HasOne("AioKin.Data.Entities.Family.Family", "Family")
                        .WithMany("Members")
                        .HasForeignKey("FamilyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_family_members_families_family_id");

                    b.HasOne("AioKin.Data.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_family_members_users_user_id");

                    b.Navigation("Family");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Security.DeviceCredential", b =>
                {
                    b.HasOne("AioKin.Data.Entities.Security.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_credentials_users_user_id");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Security.Staff", b =>
                {
                    b.HasOne("AioKin.Data.Entities.Core.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_staff_locations_location_id");

                    b.HasOne("AioKin.Data.Entities.Security.Role", "Role")
                        .WithMany("Staffs")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_staff_roles_role_id");

                    b.Navigation("Location");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Vault.Category", b =>
                {
                    b.HasOne("AioKin.Data.Entities.Vault.Space", "Space")
                        .WithMany()
                        .HasForeignKey("SpaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categories_spaces_space_id");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Vault.Prompt", b =>
                {
                    b.HasOne("AioKin.Data.Entities.Security.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_prompts_users_author_user_id");

                    b.HasOne("AioKin.Data.Entities.Vault.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_prompts_categories_category_id");

                    b.HasOne("AioKin.Data.Entities.Vault.Space", "Space")
                        .WithMany()
                        .HasForeignKey("SpaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prompts_spaces_space_id");

                    b.Navigation("Author");

                    b.Navigation("Category");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Vault.PromptTag", b =>
                {
                    b.HasOne("AioKin.Data.Entities.Vault.Prompt", "Prompt")
                        .WithMany("PromptTags")
                        .HasForeignKey("PromptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prompt_tags_prompts_prompt_id");

                    b.HasOne("AioKin.Data.Entities.Vault.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prompt_tags_tags_tag_id");

                    b.Navigation("Prompt");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Vault.PromptVariable", b =>
                {
                    b.HasOne("AioKin.Data.Entities.Vault.Prompt", "Prompt")
                        .WithMany("Variables")
                        .HasForeignKey("PromptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prompt_variables_prompts_prompt_id");

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Vault.Space", b =>
                {
                    b.HasOne("AioKin.Data.Entities.Family.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_spaces_families_family_id");

                    b.HasOne("AioKin.Data.Entities.Security.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_spaces_users_owner_user_id");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Vault.SpaceMember", b =>
                {
                    b.HasOne("AioKin.Data.Entities.Vault.Space", "Space")
                        .WithMany()
                        .HasForeignKey("SpaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_space_members_spaces_space_id");

                    b.HasOne("AioKin.Data.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_space_members_users_user_id");

                    b.Navigation("Space");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Vault.Tag", b =>
                {
                    b.HasOne("AioKin.Data.Entities.Vault.Space", "Space")
                        .WithMany()
                        .HasForeignKey("SpaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tags_spaces_space_id");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Family.Family", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Security.Role", b =>
                {
                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("AioKin.Data.Entities.Vault.Prompt", b =>
                {
                    b.Navigation("PromptTags");

                    b.Navigation("Variables");
                });
#pragma warning restore 612, 618
        }
    }
}
